In [298]:
# import required modules
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
df = pd.read_csv('heart.csv')
# df['chest pain type'] = df['chest pain type'].map({1 :'Good', 2: 'Bad', 3: 'Bad+', 4 : 'Bad++'}) 
X = df.drop('target', axis=1)
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
# df
# X_train = pd.DataFrame(X_train)
# y_train = pd.DataFrame(y_train)
print(X_train.head(10))

      age  sex  chest pain type  resting bp s  cholesterol  \
110    59    0                2           130          188   
370    63    1                4           150            0   
239    48    1                4           160          355   
807    54    1                4           140          239   
620    64    1                4           128          263   
584    69    1                3           142          271   
940    44    1                2           130          219   
485    65    1                4           134            0   
261    46    1                2           140          275   
1183   59    1                4           164          176   

      fasting blood sugar  resting ecg  max heart rate  exercise angina  \
110                     0            0             124                0   
370                     0            0              86                1   
239                     0            0              99                1   
807              

## Normalization

In [299]:
from sklearn.preprocessing import MinMaxScaler
min_max = MinMaxScaler()
X_train_scaled = min_max.fit_transform(X_train)
X_test_scaled = min_max.transform(X_test)
X_test_scaled

array([[0.66666667, 1.        , 1.        , ..., 0.        , 0.43902439,
        0.66666667],
       [0.52083333, 1.        , 0.66666667, ..., 1.        , 0.5       ,
        0.66666667],
       [0.54166667, 0.        , 0.33333333, ..., 0.        , 0.31707317,
        0.33333333],
       ...,
       [0.45833333, 1.        , 0.33333333, ..., 0.        , 0.31707317,
        0.33333333],
       [0.47916667, 1.        , 0.66666667, ..., 0.        , 0.31707317,
        0.33333333],
       [0.54166667, 1.        , 1.        , ..., 1.        , 0.62195122,
        0.33333333]])

## Standardization

In [300]:
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
X_train_scaled = std.fit_transform(X_train)
X_test_scaled = std.transform(X_test)
X_test_scaled

array([[ 0.77219968,  0.57107191,  0.81011793, ..., -0.77278353,
         0.11381699,  0.6542429 ],
       [ 0.02762622,  0.57107191, -0.24488859, ...,  1.29402343,
         0.58092378,  0.6542429 ],
       [ 0.13399386, -1.75109295, -1.29989512, ..., -0.77278353,
        -0.8203966 , -0.99585708],
       ...,
       [-0.29147668,  0.57107191, -1.29989512, ..., -0.77278353,
        -0.8203966 , -0.99585708],
       [-0.18510905,  0.57107191, -0.24488859, ..., -0.77278353,
        -0.8203966 , -0.99585708],
       [ 0.13399386,  0.57107191,  0.81011793, ...,  1.29402343,
         1.51513737, -0.99585708]])

## Box-Cox Transformer.

In [301]:
from imperio import BoxCoxTransformer
from sklearn.linear_model import LogisticRegression
boxcox = BoxCoxTransformer()
new_df = boxcox.apply(df, target = 'target', columns=['age'])
# X_transformed = boxcox.fit_transform(X_train, y_train)
# X_transformed
new_df
# from sklearn.pipeline import Pipeline
# pipe = Pipeline([('boxcox', BoxCoxTransformer()),('model', LogisticRegression())])
# pipe

age  sex  chest pain type  resting bp s  cholesterol  \
0     10.649111  1.0              2.0         140.0        289.0   
1     12.000000  0.0              3.0         160.0        180.0   
2     10.165525  1.0              2.0         130.0        283.0   
3     11.856406  0.0              4.0         138.0        214.0   
4     12.696938  1.0              3.0         150.0        195.0   
...         ...  ...              ...           ...          ...   
1185  11.416408  1.0              1.0         110.0        264.0   
1186  14.492423  1.0              4.0         144.0        193.0   
1187  13.099669  1.0              4.0         130.0        131.0   
1188  13.099669  0.0              2.0         130.0        236.0   
1189  10.328828  1.0              3.0         138.0        175.0   

      fasting blood sugar  resting ecg  max heart rate  exercise angina  \
0                     0.0          0.0           172.0              0.0   
1                     0.0          0.0           156.0              0.0   
2                     0.0          1.0            98.0              0.0   
3                     0.0          0.0           108.0              1.0   
4                     0.0          0.0           122.0              0.0   
...                   ...          ...             ...              ...   
1185                  0.0          0.0           132.0              0.0   
1186                  1.0          0.0           141.0              0.0   
1187                  0.0          0.0           115.0              1.0   
1188                  0.0          2.0           174.0              0.0   
1189                  0.0          0.0           173.0              0.0   

      oldpeak  ST slope  target  
0         0.0       1.0       0  
1         1.0       2.0       1  
2         0.0       1.0       0  
3         1.5       2.0       1  
4         0.0       1.0       0  
...       ...       ...     ...  
1185      1.2       2.0       1  
1186      3.4       2.0       1  
1187      1.2       2.0       1  
1188      0.0       2.0       1  
1189      0.0       1.0       0  

[1190 rows x 12 columns]

## ZCA Transformation.

In [302]:
from imperio import ZCATransformer
zca = ZCATransformer()
zca.fit(X_train, y_train)
X_transformed = zca.transform(X_test)
X_transformed

array([[ 0.01737165, -0.00706643,  0.02609344, ..., -0.0699582 ,
        -0.00364529,  0.0040076 ],
       [ 0.02650653,  0.02930031, -0.01610618, ...,  0.07218558,
         0.02473622,  0.03139927],
       [ 0.02646571, -0.07899094, -0.05312327, ..., -0.00639296,
        -0.03792088, -0.02346604],
       ...,
       [ 0.00376142,  0.03916023, -0.0529569 , ..., -0.01988165,
        -0.03169235, -0.03022141],
       [-0.00887199,  0.0296944 , -0.0036675 , ..., -0.02522418,
        -0.02911176, -0.03945372],
       [ 0.00127126,  0.02816216,  0.03209013, ...,  0.05949326,
         0.08239807, -0.10379228]])

 ## Frequency Imputation 

In [326]:
from imperio import FrequencyImputationTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
scaler = StandardScaler().fit(df)
new_df = scaler.transform(df)
new_df = pd.DataFrame(new_df, columns = df.columns)
new_df
# help(FrequencyImputationTransformer)
X = new_df.drop('target', axis=1)
y = new_df['target']
# print(df)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
# freq = FrequencyImputationTransformer(index = ['chest pain type'],min_int_freq = 2)
# freq.fit_transform(X_train, y_train)
# X_transformed = freq.transform(X_test)
# X_transformed
pipe = Pipeline([('ava',FrequencyImputationTransformer(index = [11],min_int_freq = 2))])
pipe.fit(X_train,y_train)
out = pipe.transform(X_test)
out

KeyError: 0

## Dummy Variable.

In [116]:
df = pd.get_dummies(df, columns=['chest pain type'], drop_first= True)
df

age  sex  resting bp s  cholesterol  fasting blood sugar  resting ecg  \
0      40    1           140          289                    0            0   
1      49    0           160          180                    0            0   
2      37    1           130          283                    0            1   
3      48    0           138          214                    0            0   
4      54    1           150          195                    0            0   
...   ...  ...           ...          ...                  ...          ...   
1185   45    1           110          264                    0            0   
1186   68    1           144          193                    1            0   
1187   57    1           130          131                    0            0   
1188   57    0           130          236                    0            2   
1189   38    1           138          175                    0            0   

      max heart rate  exercise angina  oldpeak  ST slope  target  \
0                172                0      0.0         1       0   
1                156                0      1.0         2       1   
2                 98                0      0.0         1       0   
3                108                1      1.5         2       1   
4                122                0      0.0         1       0   
...              ...              ...      ...       ...     ...   
1185             132                0      1.2         2       1   
1186             141                0      3.4         2       1   
1187             115                1      1.2         2       1   
1188             174                0      0.0         2       1   
1189             173                0      0.0         1       0   

      chest pain type_2  chest pain type_3  chest pain type_4  
0                     1                  0                  0  
1                     0                  1                  0  
2                     1                  0                  0  
3                     0                  0                  1  
4                     0                  1                  0  
...                 ...                ...                ...  
1185                  0                  0                  0  
1186                  0                  0                  1  
1187                  0                  0                  1  
1188                  1                  0                  0  
1189                  0                  1                  0  

[1190 rows x 14 columns]

## Target Imputation Transformer

In [207]:
from imperio import TargetImputationTransformer
target = TargetImputationTransformer(index = [2], min_int_freq = 3)
help(TargetImputationTransformer)
target.fit(X_train, y_train)
X_transformed = target.transform(X_test)

Help on class TargetImputationTransformer in module imperio.TargetImputation:

class TargetImputationTransformer(sklearn.base.BaseEstimator, sklearn.base.TransformerMixin)
 |  TargetImputationTransformer(reg=True, index='auto', min_int_freq=5)
 |  
 |  Method resolution order:
 |      TargetImputationTransformer
 |      sklearn.base.BaseEstimator
 |      sklearn.base.TransformerMixin
 |      sklearn.utils._set_output._SetOutputMixin
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, reg=True, index='auto', min_int_freq=5)
 |          Setting up the algorithm
 |      :param reg: bool, default = True
 |          A parameter that indicates wherever it is a classification or regression task.
 |      :param index: list, default = 'auto'
 |          A parameter that specifies the list of indexes of categorical columns that should be transformed.
 |      :param min_int_freq: int, default = 5
 |          A parameter that indicates the number of minimal values in a c

KeyError: 0

In [313]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from imperio import FrequencyImputationTransformer
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
df = pd.read_csv('heart.csv')
df = pd.DataFrame(df)
X = df.drop('target', axis=1)
Y = df['target']
X_train,X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.33, random_state = 10)
pipe = Pipeline([('transformer1',StandardScaler()),('tran2',FrequencyImputationTransformer(index = ['chest pain type'],min_int_freq = 2))])
# X_train.reshape(-1,1)
# Y_train.reshape(-1,1)
pipe.fit(X_train,Y_train)
output = pipe.predict(X_test)
print(output.shape,Y_test.shape)
# score = pipe.score(X_test, Y_test)
# print('Accuracy:', score)
print(classification_report(output,Y_test))

TypeError: '>=' not supported between instances of 'str' and 'int'

## Draft

In [323]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from imperio import FrequencyImputationTransformer
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
df = pd.read_csv('heart.csv')
df = pd.DataFrame(df)
X = df.drop('target', axis=1)
Y = df['target']
X_train,X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.33, random_state = 10)
print(X_test.head(10))
pipe = Pipeline([('tran1',StandardScaler()),('tran2',FrequencyImputationTransformer(index = [2],min_int_freq = 2))])
# X_train.reshape(-1,1)
# Y_train.reshape(-1,1)
pipe.fit(X_train,Y_train)
output = pipe.transform(X_test)
# score = pipe.score(X_test, Y_test)
# print('Accuracy:', score)
output = pd.DataFrame(output, columns= list(X))
print(output['chest pain type'])

      age  sex  chest pain type  resting bp s  cholesterol  \
896    53    1                4           140          203   
1041   64    1                4           120          246   
937    41    0                2           105          198   
87     53    0                2           140          216   
345    51    1                4           120            0   
520    63    1                4            96          305   
74     55    1                4           140          268   
440    74    1                3           138            0   
274    55    1                3           120          220   
335    51    1                4           130            0   

      fasting blood sugar  resting ecg  max heart rate  exercise angina  \
896                     1            2             155                1   
1041                    0            2              96                1   
937                     0            0             168                0   
87               