Task1 -  Create a Jupyter notebook with a clean code - Done

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
scaler = StandardScaler()
my_data = pd.read_csv("UsedCars_Combined.csv")
print(my_data.head())
print(my_data.shape)

   Id  year          brand                                    full_model_name  \
0   0  2016          Honda                                    Honda Brio S MT   
1   1  2012         Nissan                             Nissan Sunny XV Diesel   
2   2  2017         Toyota             Toyota Fortuner 2.8 4x2 MT [2016-2020]   
3   3  2017  Mercedes-Benz  Mercedes-Benz E-Class E 220d Expression [2019-...   
4   4  2012        Hyundai                  Hyundai Verna Fluidic 1.6 CRDi SX   

  model_name      price  distance_travelled(kms) fuel_type    city  
0       Brio   425000.0                   9680.0    Petrol  Mumbai  
1      Sunny   325000.0                 119120.0    Diesel  Mumbai  
2   Fortuner  2650000.0                  64593.0    Diesel   Thane  
3    E-Class  4195000.0                  25000.0    Diesel  Mumbai  
4      Verna   475000.0                  23800.0    Diesel  Mumbai  
(1725, 9)


# Study the correlation between features, find the features subset with the highest correlation with the target column, and try to explain from the business point of view why they have such a big correlation.

In [2]:
my_data['fuel_type'] = my_data['fuel_type'].map({'Diesel':0, 'Petrol':1})
print(my_data)
modify = my_data.corr()
modify

        Id  year             brand  \
0        0  2016             Honda   
1        1  2012            Nissan   
2        2  2017            Toyota   
3        3  2017     Mercedes-Benz   
4        4  2012           Hyundai   
...    ...   ...               ...   
1720  1720  2015           Hyundai   
1721  1721  2011           Bentley   
1722  1722  2008  Mahindra-Renault   
1723  1723  1990          Mahindra   
1724  1724  2017           Hyundai   

                                        full_model_name   model_name  \
0                                       Honda Brio S MT         Brio   
1                                Nissan Sunny XV Diesel        Sunny   
2                Toyota Fortuner 2.8 4x2 MT [2016-2020]     Fortuner   
3     Mercedes-Benz E-Class E 220d Expression [2019-...      E-Class   
4                     Hyundai Verna Fluidic 1.6 CRDi SX        Verna   
...                                                 ...          ...   
1720                                  H

/tmp/ipykernel_30914/2442817070.py:3: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  modify = my_data.corr()


Id      year     price  \
Id                       1.000000 -0.054391 -0.105696   
year                    -0.054391  1.000000  0.288483   
price                   -0.105696  0.288483  1.000000   
distance_travelled(kms)  0.100282 -0.386107 -0.137351   
fuel_type               -0.074820 -0.065165 -0.265953   

                         distance_travelled(kms)  fuel_type  
Id                                      0.100282  -0.074820  
year                                   -0.386107  -0.065165  
price                                  -0.137351  -0.265953  
distance_travelled(kms)                 1.000000  -0.235823  
fuel_type                              -0.235823   1.000000

##  Create a second set of data with the columns that have an absolute correlation between 0.5 and 0.8 with the target column.

It can be noticed that the highest correlation with out target column ,price, has column ,year, since it influence the most the value of a car.

In [3]:
k = 0
lista = []
for i in modify['price']:
    if (-0.1<i<0.5):
        lista.append(k)
    k = k + 1
df2 = pd.DataFrame()
for i in range(len(lista)):
    df2.loc[:,i] = modify.iloc[lista[i]]
#df2 represents the column in our case ,year, and its corelation toward other columns
df2
print(df2)

                                0
Id                      -0.054391
year                     1.000000
price                    0.288483
distance_travelled(kms) -0.386107
fuel_type               -0.065165


## Split the data into 2 sub-sets using the train test split function from sklearn.

In [13]:
X = my_data[['year','distance_travelled(kms)']].values
y = my_data['price'].values.reshape(-1,1)
# X = scaler.fit_transform(X)

#Now I have splitted my data set in 2 subsets, train and test
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)
print("Feature column========================\n",y_train)
print(X_train)
print("Target column========================\n",y_train)


Feature column========================
 [[4200000.]
 [2800000.]
 [4400000.]
 ...
 [1000000.]
 [ 699000.]
 [ 699000.]]
[[  2018.  24000.]
 [  2014.  27000.]
 [  2018.  28800.]
 ...
 [  2015. 142502.]
 [  2015.  74541.]
 [  2015.  74541.]]
Target column========================
 [[4200000.]
 [2800000.]
 [4400000.]
 ...
 [1000000.]
 [ 699000.]
 [ 699000.]]


## Train a sklearn Linear Regression model on the data provided to you

In [14]:
from sklearn.linear_model import LinearRegression
lin = LinearRegression()
lin.fit(X_train,y_train)
storage = lin.predict(X_test)
print(storage)
# print(storage.shape)
# print(y_test.shape)

[[ 312454.72032505]
 [1410002.13586354]
 [1320459.01247698]
 [1955996.58689719]
 [ 544571.31082565]
 [ 999260.98117656]
 [1312815.80673081]
 [1746914.3488816 ]
 [2239087.65670955]
 [2105247.65168834]
 [2091791.30354363]
 [2249002.86060566]
 [1301664.03526312]
 [1033804.13509285]
 [1945911.40807718]
 [1686006.66780555]
 [1755287.030343  ]
 [ 943150.84232855]
 [ 578458.72745043]
 [1030971.21969396]
 [ 877300.80688059]
 [ 988477.4887107 ]
 [ 874467.8914817 ]
 [1469319.13494307]
 [1627311.1601975 ]
 [2109497.02478665]
 [1910499.96559107]
 [1933398.42076027]
 [1463653.30414534]
 [1944494.9503777 ]
 [ 288115.39421695]
 [1907916.68020588]
 [1657417.96859914]
 [2077839.19520414]
 [1621716.15228468]
 [1300850.98854363]
 [1810654.94535649]
 [1930330.37338328]
 [1056968.88430953]
 [1429091.73627895]
 [1792240.99526376]
 [1002642.06570512]
 [ 888632.46847612]
 [ 880504.83419669]
 [1769577.67207271]
 [2037257.68211508]
 [1596076.85146707]
 [1550750.20508492]
 [1444515.87762678]
 [1229244.80246371]


# Train a from-scratch implementation of Linear Regression on the train sub-set.

In [25]:
import numpy as np
#print(y_train.values.reshape(-1,1).shape)
class MultipleLinearRegression:
    def __init__(self, alpha=0.00000000000000001, n_iterations=1000):
        self.alpha = alpha
        self.n_iterations = n_iterations

    def fit(self, X, y):
        # Add a column of ones for the intercept term
        ones = np.ones((X.shape[0], 1))
        X = np.concatenate((ones, X), axis=1)

        # Initialize the weights
        self.weights = np.ones((X.shape[1], 1))

        # Gradient descent
        for i in range(self.n_iterations):
            y_pred = np.dot(X, self.weights)
            error = y_pred - y
            gradient = np.dot(X.transpose(), error) / y.size
            self.weights = self.weights -  self.alpha * gradient

    def predict(self, X):
        # Add a column of ones for the intercept term
        ones = np.ones((X.shape[0], 1))
        X = np.concatenate((ones, X), axis=1)
        print(np.dot(X,self.weights))
        # Predict using the learned weights
        return np.dot(X, self.weights)
    def r2_score(y_true, y_pred):
        ss_res = np.sum((y_true - y_pred) ** 2)
        ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)
        r2 = 1 - (ss_res / ss_tot)
        print(r2)
        return r2
#y_train = y_train.reshape(-1,1)
nem =  MultipleLinearRegression()
nem.fit(X_train,y_train)
obj = nem.predict(X_test)


[[172427.91817759]
 [100958.58372638]
 [ 63659.88357852]
 [ 16908.92057854]
 [511232.2856298 ]
 [ 89457.96942981]
 [ 69059.45940653]
 [ 64059.14608931]
 [ 18031.66284088]
 [ 12026.68672372]
 [ 21532.98219558]
 [ 11027.02407214]
 [ 76937.67669601]
 [ 65054.80862219]
 [ 24033.63886903]
 [107087.64138301]
 [ 58144.22898045]
 [129097.22022212]
 [ 85065.06215815]
 [ 67056.13398469]
 [ 75060.43540501]
 [ 97076.01442216]
 [ 77061.7607675 ]
 [ 59053.83262372]
 [ 47996.50936291]
 [  9024.69867997]
 [ 49050.20590025]
 [ 32873.49299518]
 [ 63056.48334872]
 [ 25034.30155028]
 [ 89065.7128238 ]
 [151432.00683654]
 [ 26727.42407297]
 [ 31389.50960588]
 [ 51949.12695385]
 [ 77512.05707504]
 [ 19029.32543311]
 [ 35040.92836277]
 [ 48689.97113305]
 [ 87472.65277119]
 [ 32037.94028935]
 [ 87069.38760967]
 [ 67055.13395502]
 [ 72796.93642002]
 [ 48048.54318933]
 [ 60058.49542366]
 [ 70062.12214713]
 [102083.3279471 ]
 [177133.02904076]
 [128098.55760022]
 [ 15026.67470812]
 [ 48933.13153158]
 [ 35038.928

# Test the models on the test sets from the initial data set. For error metrics, use the model’s ’score’ function from the Linear Regression model.

In [31]:
## alfa = mean_squared_error(storage,y_test)
# beta = mean_absolute_error(storage,y_test)
# print(alfa)

score = lin.score(X_test,y_test)
#Score function for from scratch model
print(r2_score(obj,y_test))
#Score function for sklearn model
print(score)


-1071.0590811160478
0.1005140160934701


# Train a sklearn Linear Regression model on the data with selected columns (train subset)

In [32]:
from sklearn.linear_model import LinearRegression
trail = LinearRegression()
trail.fit(X_train,y_train)
out_value = trail.predict(X_test)
print(out_value)

[[ 312454.72032505]
 [1410002.13586354]
 [1320459.01247698]
 [1955996.58689719]
 [ 544571.31082565]
 [ 999260.98117656]
 [1312815.80673081]
 [1746914.3488816 ]
 [2239087.65670955]
 [2105247.65168834]
 [2091791.30354363]
 [2249002.86060566]
 [1301664.03526312]
 [1033804.13509285]
 [1945911.40807718]
 [1686006.66780555]
 [1755287.030343  ]
 [ 943150.84232855]
 [ 578458.72745043]
 [1030971.21969396]
 [ 877300.80688059]
 [ 988477.4887107 ]
 [ 874467.8914817 ]
 [1469319.13494307]
 [1627311.1601975 ]
 [2109497.02478665]
 [1910499.96559107]
 [1933398.42076027]
 [1463653.30414534]
 [1944494.9503777 ]
 [ 288115.39421695]
 [1907916.68020588]
 [1657417.96859914]
 [2077839.19520414]
 [1621716.15228468]
 [1300850.98854363]
 [1810654.94535649]
 [1930330.37338328]
 [1056968.88430953]
 [1429091.73627895]
 [1792240.99526376]
 [1002642.06570512]
 [ 888632.46847612]
 [ 880504.83419669]
 [1769577.67207271]
 [2037257.68211508]
 [1596076.85146707]
 [1550750.20508492]
 [1444515.87762678]
 [1229244.80246371]


# Test the models on the test sets from the initial data set. For error metrics, use the model’s ’score’ function from the sklearn Linear Regression model.

In [33]:
beta = r2_score(y_test,out_value)
alpha = r2_score(y_test,obj)
print(beta)
print(alpha)

0.1005140160934701
-0.9365179876427718


# Please try to interpret the results you are getting by comparing the error of the models you created.

It can be noticed that predicted values in sklearn model have a better precision than the one made from scratch

# Split the data with the selected columns into 2 sub-sets using the train test split function from sklearn.

In [34]:
x_col = my_data.drop(['year','distance_travelled(kms)','price'],axis=1)
X_val,y_val = train_test_split(x_col,test_size=0.2,random_state=0)
print(X_val)
print(y_val)

        Id          brand                            full_model_name  \
427    427            BMW  BMW 5 Series 520d Luxury Line [2017-2019]   
1105  1105            BMW  BMW 5 Series 520d Luxury Line [2017-2019]   
1463  1463     Land Rover             Land Rover Discovery Sport HSE   
361    361  Mercedes-Benz   Mercedes-Benz CLA 200 Petrol Sport (CBU)   
315    315           Audi                      Audi A6 35 TDI Matrix   
...    ...            ...                                        ...   
835    835  Maruti Suzuki              Maruti Suzuki Ertiga VDI SHVS   
1216  1216     Land Rover             Land Rover Discovery Sport HSE   
1653  1653         Toyota            Toyota Innova 2.5 G BS IV 7 STR   
559    559  Maruti Suzuki                    Maruti Suzuki Ciaz ZXI+   
684    684  Maruti Suzuki                    Maruti Suzuki Ciaz ZXI+   

     model_name  fuel_type       city  
427           5        0.0      Delhi  
1105          5        0.0    Chennai  
1463  Discovery

# Questions


Is the map function replacing 0 with None?
